[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
either = "1.11.0"
sdl2 = { version = "0.36.0", features = ["bundled"]}
